version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm i -g serverless
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - npm test
  build:
    commands:
      - sls deploy -s dev --verbose
