version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g serverless
      - npm install
      - npm test
  build:
    commands:
      - npm run build
      - sls deploy --stage dev
artifacts:
  files:
    - 'dist/*'
  discard-paths: no
cache:
  paths:
    - node_modules
    - .serverless
