version: 0.2

phases:
  runtime-versions:
    nodejs: 12
  install:
    commands:
      - npm install -g serverless
      - npm install
      - npm test
  build:
    commands:
      - sls deploy -stage dev
artifacts:
  files:
    - serverless.yml

