service: cicd-nest-sls-service

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  lambdaHashingVersion: "20201221"
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - ssm:GetParameter
      Resource: "*"
    - Effect: Allow
      Action:
        - iam:GetRole
      Resource: "arn:aws:lambda:us-east-1:666398651410:function:cicd-nest-sls-service-dev-main"


  environment:
    STAGE: ${opt:stage, 'dev'}
    DB_USER: ${ssm:/${opt:stage, 'dev'}/DB_USER}
    DB_PASS: ${ssm:/${opt:stage, 'dev'}/DB_PASS}
    DB_NAME: ${ssm:/${opt:stage, 'dev'}/DB_NAME}
    DB_HOST: ${ssm:/${opt:stage, 'dev'}/DB_HOST}
    DB_PORT: ${ssm:/${opt:stage, 'dev'}/DB_PORT}
    DB_DIALECT: ${ssm:/${opt:stage, 'dev'}/DB_DIALECT}
    JWTKEY: ${ssm:/${opt:stage, 'dev'}/JWTKEY}
    TOKEN_EXPIRATION: ${ssm:/${opt:stage, 'dev'}/TOKEN_EXPIRATION}
    BEARER: ${ssm:/${opt:stage, 'dev'}/BEARER}

functions:
  main:
    handler: dist/serverless.handler
    timeout: 30
    events:
      - http:
          method: any
          path: /{any+}
